
# App
spring.application.name=product-service
server.port=8080

# PostgreSQL
spring.datasource.url=spring.datasource.url=jdbc:postgresql://product-postgres-db.cdeqwysc8nah.ap-south-1.rds.amazonaws.com:5432/productdb?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator (for AWS health checks later)
management.endpoints.web.exposure.include=health